import { app, auth, db, audit } from './firebase-client.js';
import { initializeApp, deleteApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signOut, sendPasswordResetEmail } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { collection, getDocs, doc, setDoc, updateDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';
const $ = id => document.getElementById(id), escape = value => String(value || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const message = $('adminMessage');
function show(text, success=false){message.textContent=text;message.className='auth-message show'+(success?' success':'');}
function formatDate(value){if(!value||!value.toDate)return '—';return value.toDate().toLocaleString('pt-BR');}
async function load(){const snapshot=await getDocs(collection(db,'users'));const users=snapshot.docs.map(item=>({id:item.id,...item.data()})).sort((a,b)=>String(a.name||a.email).localeCompare(String(b.name||b.email),'pt-BR'));$('userRows').innerHTML=users.map(user=>`<tr><td>${escape(user.name)}</td><td>${escape(user.email)}</td><td>${user.role==='admin'?'Administrador':'Usuário'}</td><td><span class="admin-badge ${user.status==='active'?'active':'blocked'}">${user.status==='active'?'Ativo':'Bloqueado'}</span></td><td>${formatDate(user.lastAccessAt)}</td><td><div class="admin-table-actions"><button class="btn ghost small" data-edit="${user.id}" data-name="${escape(user.name)}" data-user-email="${escape(user.email)}" data-role="${user.role}">Editar</button><button class="btn ghost small" data-reset="${user.id}" data-email="${escape(user.email)}">Redefinir senha</button><button class="btn ghost small ${user.status==='active'?'danger':''}" data-status="${user.id}" data-next="${user.status==='active'?'blocked':'active'}">${user.status==='active'?'Bloquear':'Liberar'}</button></div></td></tr>`).join('')||'<tr><td colspan="6" class="muted">Nenhum usuário aprovado.</td></tr>';}
$('createUserForm').addEventListener('submit',async event=>{event.preventDefault();const name=$('newName').value.trim(),email=$('newEmail').value.trim().toLowerCase(),role=$('newRole').value;try{const tempApp=initializeApp(window.PORTAL_FIREBASE_CONFIG,'provision-'+Date.now());const tempAuth=getAuth(tempApp);const random=crypto.getRandomValues(new Uint32Array(8));const password=Array.from(random,n=>n.toString(36)).join('')+'Aa!9';const created=await createUserWithEmailAndPassword(tempAuth,email,password);await setDoc(doc(db,'users',created.user.uid),{name,email,role,status:'active',createdAt:serverTimestamp(),lastAccessAt:null});await sendPasswordResetEmail(auth,email);await audit('user_created',{targetUid:created.user.uid,role});await signOut(tempAuth);await deleteApp(tempApp);event.target.reset();show('Usuário criado. Enviamos um link para definição segura de senha.',true);await load();}catch(error){show(error.code==='auth/email-already-in-use'?'Este e-mail já possui uma conta.':'Não foi possível criar o usuário: '+(error.message||'erro inesperado'));}});
$('refreshUsers').addEventListener('click',()=>load().catch(error=>show('Não foi possível carregar usuários.')));
$('userRows').addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{if(button.dataset.edit){const newName=prompt('Nome:',button.dataset.name);if(newName===null)return;const name=newName.trim();if(!name)return;const newEmail=prompt('E-mail (só o cadastro informativo aqui — não muda o login real):',button.dataset.userEmail);if(newEmail===null)return;const email=newEmail.trim().toLowerCase();if(!email)return;const newRole=prompt('Perfil ("admin" ou "user"):',button.dataset.role);if(newRole===null)return;const role=newRole.trim().toLowerCase()==='admin'?'admin':'user';await updateDoc(doc(db,'users',button.dataset.edit),{name,email,role});await audit('user_updated',{targetUid:button.dataset.edit,name,email,role});show('Usuário atualizado.',true);await load();}if(button.dataset.reset){await sendPasswordResetEmail(auth,button.dataset.email);await audit('password_reset_requested',{targetUid:button.dataset.reset});show('Link de redefinição enviado.',true);}if(button.dataset.status){await updateDoc(doc(db,'users',button.dataset.status),{status:button.dataset.next});await audit('user_status_changed',{targetUid:button.dataset.status,status:button.dataset.next});await load();}}catch(_){show('Não foi possível concluir esta ação.');}});
load().catch(()=>show('Não foi possível carregar usuários. Verifique seu perfil administrativo.'));
