param([int]$Port = 8766)
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Net.Http
$listener=[System.Net.HttpListener]::new();$listener.Prefixes.Add("http://127.0.0.1:$Port/");$listener.IgnoreWriteExceptions=$true
try{$listener.Start()}catch [System.Net.HttpListenerException]{exit 0}
$client=[System.Net.Http.HttpClient]::new();$client.Timeout=[TimeSpan]::FromSeconds(30)
function Send-Json($response,[int]$status,$value){$bytes=[Text.Encoding]::UTF8.GetBytes(($value|ConvertTo-Json -Depth 8 -Compress));$response.StatusCode=$status;$response.ContentType='application/json; charset=utf-8';$response.ContentLength64=$bytes.Length;$response.OutputStream.Write($bytes,0,$bytes.Length)}
function Get-JsonObject([string]$html){$at=$html.IndexOf('skuJson_0',[StringComparison]::OrdinalIgnoreCase);if($at-lt 0){return $null};$start=$html.IndexOf('{',$at);$depth=0;$quoted=$false;$escaped=$false;for($i=$start;$i-lt$html.Length;$i++){$ch=$html[$i];if($quoted){if($escaped){$escaped=$false}elseif($ch -eq '\'){$escaped=$true}elseif($ch -eq '"'){$quoted=$false};continue};if($ch -eq '"'){$quoted=$true}elseif($ch -eq '{'){$depth++}elseif($ch -eq '}'){$depth--;if($depth-eq 0){return $html.Substring($start,$i-$start+1)}}};return $null}
function Price($cents){if($null-eq$cents){return $null};return [Math]::Round(([decimal]$cents)/100,2)}
function Brand([string]$html){$m=[regex]::Match($html,'itemprop=["'']brand["''][\s\S]{0,700}?itemprop=["'']name["'']\s+content=["'']([^"'']+)',[Text.RegularExpressions.RegexOptions]::IgnoreCase);if($m.Success){return [Net.WebUtility]::HtmlDecode($m.Groups[1].Value).Trim()};return ''}
function Get-FgOffer([string]$sourceUrl){try{$uri=[uri]$sourceUrl}catch{throw 'Link inválido.'};if($uri.Scheme -notin @('http','https') -or $uri.Host -notmatch '(^|\.)fg\.com\.br$'){throw 'Use um link válido de fg.com.br.'};$req=[Net.Http.HttpRequestMessage]::new([Net.Http.HttpMethod]::Get,$uri.AbsoluteUri);$req.Headers.UserAgent.ParseAdd('FG-Post-Editor/1.0');$res=$client.SendAsync($req).GetAwaiter().GetResult();if(-not$res.IsSuccessStatusCode){$res.Dispose();throw 'A página da oferta não pôde ser carregada.'};$html=$res.Content.ReadAsStringAsync().GetAwaiter().GetResult();$res.Dispose();$raw=Get-JsonObject $html;if(!$raw){throw 'Os dados de SKU não foram encontrados nesta página.'};try{$data=$raw|ConvertFrom-Json}catch{throw 'Os dados de SKU recebidos estão inválidos.'};$skus=@();foreach($item in @($data.skus)){$price=Price $item.bestPrice;if($null-eq$price){continue};$list=Price $item.listPrice;$old=$null;if($null-ne$list -and $list-gt$price){$old=$list};$discount=$null;if($null-ne$old){$discount=[Math]::Floor((($old-$price)/$old)*100)};$skus+=@([pscustomobject]@{sku=[string]$item.sku;variation=(@($item.dimensions.psobject.Properties|ForEach-Object{[string]$_.Value}|Where-Object{$_}) -join ' · ');price=$price;listPrice=$old;discountPercent=$discount;available=[bool]$item.available})};if(!$skus.Count){throw 'Nenhum SKU com preço disponível foi encontrado.'};[pscustomobject]@{sourceUrl=$uri.AbsoluteUri;title=[string]$data.name;brand=(Brand $html);skus=$skus;fetchedAt=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()}}
while($listener.IsListening){$ctx=$null;try{$ctx=$listener.GetContext();$req=$ctx.Request;$out=$ctx.Response;$out.Headers['Access-Control-Allow-Origin']='*';$out.Headers['Access-Control-Allow-Private-Network']='true';if($req.HttpMethod-eq'OPTIONS'){$out.StatusCode=204}elseif($req.Url.AbsolutePath-eq'/health'){Send-Json $out 200 @{ok=$true}}elseif($req.Url.AbsolutePath-eq'/product-offer'){try{$url=[string]$req.QueryString['url'];if(!$url){throw 'Informe o link do produto.'};Send-Json $out 200 (Get-FgOffer $url)}catch{Send-Json $out 400 @{error=$_.Exception.Message}}}else{Send-Json $out 404 @{error='Rota não encontrada.'}};$out.Close()}catch{if($ctx){try{Send-Json $ctx.Response 502 @{error='Não foi possível consultar a oferta.'};$ctx.Response.Close()}catch{}}}}
